<?php

session_start();

unset($_SESSION['mapa_inicial']);
unset($_SESSION['mapa1']);
unset($_SESSION['mapa2']);
unset($_SESSION['mapa_geral']);
unset($_SESSION['mapa_atual']);
unset($_SESSION['teste_goblins']);
unset($_SESSION['ataque_surpresa']);
unset($_SESSION['falha_automatica']);
unset($_SESSION['opcao_magia']);
unset($_SESSION['magia_usada']);
unset($_SESSION['atacar_magia']);
unset($_SESSION['magia']);
unset($_SESSION['fim']);
unset($_SESSION['setar_magia']);
unset($_SESSION['dano']);
unset($_SESSION['bonus']);
unset($_SESSION['escolher_arma']);
unset($_SESSION['erro']);
unset($_SESSION['defesa_total']);
unset($_SESSION['dado']);
unset($_SESSION['defesa']);
unset($_SESSION['efeito_bonus']);
unset($_SESSION['vida_perdida']);
unset($_SESSION['escolher_cura']);
unset($_SESSION['mensagem']);
unset($_SESSION['escolher_protecao']);
unset($_SESSION['passar_defesa']);
unset($_SESSION['tesouro']);
unset($_SESSION['valor_tesouro']);
unset($_SESSION['fim_turno']);
unset($_SESSION['monstro']);
unset($_SESSION['nome_monstro']); 
unset($_SESSION['nivel_monstro']);
unset($_SESSION['quantidade_monstro']);
unset($_SESSION['tesouro_monstro']);
unset($_SESSION['hab1_monstro']);
unset($_SESSION['hab2_monstro']);
unset($_SESSION["arco_personagem1"]);
unset($_SESSION["funda_personagem1"]);
unset($_SESSION["arco_personagem2"]);
unset($_SESSION["funda_personagem2"]);
unset($_SESSION["arco_personagem3"]);
unset($_SESSION["funda_personagem3"]);
unset($_SESSION["arco_personagem4"]);
unset($_SESSION["funda_personagem4"]);
unset($_SESSION['ataque_surpresa']);
unset($_SESSION['ordem_setada']);
unset($_SESSION['turno1_surpresa']);
unset($_SESSION['turno2_surpresa']);
unset($_SESSION['turno3_surpresa']);
unset($_SESSION['turno4_surpresa']);
unset($_SESSION['teste_goblins']);
unset($_SESSION['monstros_defender']);

header('Location: tabletop.php');

?>